setwd("C:/Users/lycnb/Specilization in data science/Exploratory analysis/exdata-data-household_power_consumption")
PoA<-read.table("household_power_consumption.txt",sep=";",header=TRUE,nrows=200000,stringsAsFactors = FALSE)
library(dplyr)
PoA1<-subset(PoA,PoA$Date %in% c("1/2/2007","2/2/2007"))
#attach the data set, do not need to give the entire dataset name
attach(PoA1)
PoA1$Global_active_power<-as.numeric(PoA1$Global_active_power)
x<-paste(Date,Time)
PoA1$DateTime <- strptime(x, "%d/%m/%Y %H:%M:%S")
with(PoA1,plot(DateTime,Global_active_power,type="l",ylab="Globa Active Power (killowatts)"))
dev.copy(png,file="plot2.png",width=480,height=480)
dev.off()